package com.fanren.Traffic.pojo;

public class Change_Point {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_point.Id
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_point.taxi_id
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    private String taxiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_point.tel
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_point.time
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_point.speed
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    private String speed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_point.dir
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    private String dir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_point.status
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_point.lon
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    private String lon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_point.lat
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    private String lat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_point.Id
     *
     * @return the value of change_point.Id
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_point.Id
     *
     * @param id the value for change_point.Id
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_point.taxi_id
     *
     * @return the value of change_point.taxi_id
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public String getTaxiId() {
        return taxiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_point.taxi_id
     *
     * @param taxiId the value for change_point.taxi_id
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public void setTaxiId(String taxiId) {
        this.taxiId = taxiId == null ? null : taxiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_point.tel
     *
     * @return the value of change_point.tel
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_point.tel
     *
     * @param tel the value for change_point.tel
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_point.time
     *
     * @return the value of change_point.time
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_point.time
     *
     * @param time the value for change_point.time
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_point.speed
     *
     * @return the value of change_point.speed
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public String getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_point.speed
     *
     * @param speed the value for change_point.speed
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public void setSpeed(String speed) {
        this.speed = speed == null ? null : speed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_point.dir
     *
     * @return the value of change_point.dir
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public String getDir() {
        return dir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_point.dir
     *
     * @param dir the value for change_point.dir
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public void setDir(String dir) {
        this.dir = dir == null ? null : dir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_point.status
     *
     * @return the value of change_point.status
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_point.status
     *
     * @param status the value for change_point.status
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_point.lon
     *
     * @return the value of change_point.lon
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public String getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_point.lon
     *
     * @param lon the value for change_point.lon
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public void setLon(String lon) {
        this.lon = lon == null ? null : lon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_point.lat
     *
     * @return the value of change_point.lat
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_point.lat
     *
     * @param lat the value for change_point.lat
     *
     * @mbg.generated Sat Sep 29 20:53:43 CST 2018
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }
}