package com.fanren.Traffic.pojo;

public class Taxi_query {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taxi_query.Id
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taxi_query.id_car
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    private String idCar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taxi_query.tel
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taxi_query.time
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taxi_query.speed
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    private String speed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taxi_query.dir
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    private String dir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taxi_query.status
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taxi_query.lon
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    private String lon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taxi_query.lat
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    private String lat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taxi_query.Id
     *
     * @return the value of taxi_query.Id
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taxi_query.Id
     *
     * @param id the value for taxi_query.Id
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taxi_query.id_car
     *
     * @return the value of taxi_query.id_car
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public String getIdCar() {
        return idCar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taxi_query.id_car
     *
     * @param idCar the value for taxi_query.id_car
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public void setIdCar(String idCar) {
        this.idCar = idCar == null ? null : idCar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taxi_query.tel
     *
     * @return the value of taxi_query.tel
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taxi_query.tel
     *
     * @param tel the value for taxi_query.tel
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taxi_query.time
     *
     * @return the value of taxi_query.time
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taxi_query.time
     *
     * @param time the value for taxi_query.time
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taxi_query.speed
     *
     * @return the value of taxi_query.speed
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public String getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taxi_query.speed
     *
     * @param speed the value for taxi_query.speed
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public void setSpeed(String speed) {
        this.speed = speed == null ? null : speed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taxi_query.dir
     *
     * @return the value of taxi_query.dir
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public String getDir() {
        return dir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taxi_query.dir
     *
     * @param dir the value for taxi_query.dir
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public void setDir(String dir) {
        this.dir = dir == null ? null : dir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taxi_query.status
     *
     * @return the value of taxi_query.status
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taxi_query.status
     *
     * @param status the value for taxi_query.status
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taxi_query.lon
     *
     * @return the value of taxi_query.lon
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public String getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taxi_query.lon
     *
     * @param lon the value for taxi_query.lon
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public void setLon(String lon) {
        this.lon = lon == null ? null : lon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taxi_query.lat
     *
     * @return the value of taxi_query.lat
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taxi_query.lat
     *
     * @param lat the value for taxi_query.lat
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }
}