package com.fanren.Traffic.DAO;

import com.fanren.Traffic.pojo.Taxi_query;
import com.fanren.Traffic.pojo.Taxi_queryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Taxi_queryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi_query
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    long countByExample(Taxi_queryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi_query
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    int deleteByExample(Taxi_queryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi_query
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi_query
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    int insert(Taxi_query record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi_query
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    int insertSelective(Taxi_query record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi_query
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    List<Taxi_query> selectByExample(Taxi_queryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi_query
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    Taxi_query selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi_query
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") Taxi_query record, @Param("example") Taxi_queryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi_query
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    int updateByExample(@Param("record") Taxi_query record, @Param("example") Taxi_queryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi_query
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    int updateByPrimaryKeySelective(Taxi_query record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi_query
     *
     * @mbg.generated Sat Sep 22 09:29:38 CST 2018
     */
    int updateByPrimaryKey(Taxi_query record);
}