package com.fanren.Traffic.DAO;

import com.fanren.Traffic.pojo.taxi;
import com.fanren.Traffic.pojo.taxiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface taxiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi
     *
     * @mbg.generated Thu Sep 20 22:16:50 CST 2018
     */
    long countByExample(taxiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi
     *
     * @mbg.generated Thu Sep 20 22:16:50 CST 2018
     */
    int deleteByExample(taxiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi
     *
     * @mbg.generated Thu Sep 20 22:16:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi
     *
     * @mbg.generated Thu Sep 20 22:16:50 CST 2018
     */
    int insert(taxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi
     *
     * @mbg.generated Thu Sep 20 22:16:50 CST 2018
     */
    int insertSelective(taxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi
     *
     * @mbg.generated Thu Sep 20 22:16:50 CST 2018
     */
    List<taxi> selectByExample(taxiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi
     *
     * @mbg.generated Thu Sep 20 22:16:50 CST 2018
     */
    taxi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi
     *
     * @mbg.generated Thu Sep 20 22:16:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") taxi record, @Param("example") taxiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi
     *
     * @mbg.generated Thu Sep 20 22:16:50 CST 2018
     */
    int updateByExample(@Param("record") taxi record, @Param("example") taxiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi
     *
     * @mbg.generated Thu Sep 20 22:16:50 CST 2018
     */
    int updateByPrimaryKeySelective(taxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taxi
     *
     * @mbg.generated Thu Sep 20 22:16:50 CST 2018
     */
    int updateByPrimaryKey(taxi record);
}